package com.yixin.A1000.video.webservice.impl;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.yixin.A1000.video.webservice.CameraProxyPortType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CameraProxy service = new CameraProxy();
 * CameraProxyPortType portType = service.getCameraProxy();
 * portType.login(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CameraProxy", targetNamespace = "http://tempuri.org/api.xsd/CameraProxy.wsdl", wsdlLocation = "http://192.168.1.52:8000/platform/CameraProxy?wsdl")
public class CameraProxy extends Service {

	private final static URL CAMERAPROXY_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.yixin.A1000.video.webservice.impl.CameraProxy.class
					.getName());

	static {
		Properties pro = new Properties();
		String filename = CameraProxy.class.getResource("/").getPath() + "vci-config.properties";
		logger.info(filename);
		File file = new File(filename);
		FileInputStream fis = null;
		String wsdl = "";		
		try {
			fis = new FileInputStream(file);
			pro.load(fis);
			wsdl = pro.getProperty("vci.webServiceWsdl");			
		} catch (FileNotFoundException ex) {
		} catch (IOException ex) {
		} finally {
			if (fis != null) {
				try {
					fis.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}	
		if("".equals(wsdl)){
			wsdl = "http://127.0.0.1:8000/hlk/CameraProxy?wsdl";
		}
		logger.info(wsdl);
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.yixin.A1000.video.webservice.impl.CameraProxy.class
					.getResource(".");
			url = new URL(baseUrl,
					//"http://113.98.59.242:8000/hlk/CameraProxy?wsdl");
					wsdl);
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8000/hlk/CameraProxy?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CAMERAPROXY_WSDL_LOCATION = url;
	}

	public CameraProxy(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CameraProxy() {
		super(CAMERAPROXY_WSDL_LOCATION, new QName(
				"http://tempuri.org/api.xsd/CameraProxy.wsdl", "CameraProxy"));
	}

	/**
	 * 
	 * @return returns CameraProxyPortType
	 */
	@WebEndpoint(name = "CameraProxy")
	public CameraProxyPortType getCameraProxy() {
		return super.getPort(new QName(
				"http://tempuri.org/api.xsd/CameraProxy.wsdl", "CameraProxy"),
				CameraProxyPortType.class);
	}
	public static void main(String[] agrs) {
		  CameraProxy service = new CameraProxy();
		  CameraProxyPortType portType = service.getCameraProxy();
		  portType.ptzControl("1", 1, 1, 1);
		 
	}
}
