package com.yixin.A1000.video.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CameraProxyPortType", targetNamespace = "http://tempuri.org/api.xsd/CameraProxy.wsdl")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CameraProxyPortType {

	/**
	 * Service definition of function api__Login
	 * 
	 * @param userName
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Login")
	@WebResult(name = "loginID", partName = "loginID")
	public String login(
			@WebParam(name = "userName", partName = "userName") String userName,
			@WebParam(name = "password", partName = "password") String password);

	/**
	 * Service definition of function api__Logout
	 * 
	 * @param loginID
	 * @return returns int
	 */
	@WebMethod(operationName = "Logout")
	@WebResult(name = "result", partName = "result")
	public int logout(
			@WebParam(name = "loginID", partName = "loginID") String loginID);

	/**
	 * Service definition of function api__PTZControl
	 * 
	 * @param ptzCmd
	 * @param loginID
	 * @param isStop
	 * @param channelID
	 * @return returns int
	 */
	@WebMethod(operationName = "PTZControl")
	@WebResult(name = "result", partName = "result")
	public int ptzControl(
			@WebParam(name = "loginID", partName = "loginID") String loginID,
			@WebParam(name = "channelID", partName = "channelID") int channelID,
			@WebParam(name = "ptzCmd", partName = "ptzCmd") int ptzCmd,
			@WebParam(name = "isStop", partName = "isStop") int isStop);

	/**
	 * Service definition of function api__PTZPreset
	 * 
	 * @param loginID
	 * @param presetIndex
	 * @param ptzPresetCmd
	 * @param channelID
	 * @return returns int
	 */
	@WebMethod(operationName = "PTZPreset")
	@WebResult(name = "result", partName = "result")
	public int ptzPreset(
			@WebParam(name = "loginID", partName = "loginID") String loginID,
			@WebParam(name = "channelID", partName = "channelID") int channelID,
			@WebParam(name = "ptzPresetCmd", partName = "ptzPresetCmd") int ptzPresetCmd,
			@WebParam(name = "presetIndex", partName = "presetIndex") int presetIndex);

	/**
	 * Service definition of function api__PowerControl
	 * 
	 * @param loginID
	 * @param channelID
	 * @param powerSpan
	 * @return returns int
	 */
	@WebMethod(operationName = "PowerControl")
	@WebResult(name = "result", partName = "result")
	public int powerControl(
			@WebParam(name = "loginID", partName = "loginID") String loginID,
			@WebParam(name = "channelID", partName = "channelID") int channelID,
			@WebParam(name = "powerSpan", partName = "powerSpan") int powerSpan);

	/**
	 * Service definition of function api__QueryAlarmEvent
	 * 
	 * @param startTime
	 * @param result
	 * @param loginID
	 * @param channelID
	 * @param alarmEventList
	 * @param endTime
	 */
	@WebMethod(operationName = "QueryAlarmEvent")
	public void queryAlarmEvent(
			@WebParam(name = "loginID", partName = "loginID") String loginID,
			@WebParam(name = "channelID", partName = "channelID") int channelID,
			@WebParam(name = "startTime", partName = "startTime") String startTime,
			@WebParam(name = "endTime", partName = "endTime") String endTime,
			@WebParam(name = "alarmEventList", mode = WebParam.Mode.OUT, partName = "alarmEventList") Holder<String> alarmEventList,
			@WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result") Holder<Integer> result);

	/**
	 * Service definition of function api__QueryPowerStatus
	 * 
	 * @param result
	 * @param powerStatus
	 * @param loginID
	 * @param channelID
	 */
	@WebMethod(operationName = "QueryPowerStatus")
	public void queryPowerStatus(
			@WebParam(name = "loginID", partName = "loginID") String loginID,
			@WebParam(name = "channelID", partName = "channelID") int channelID,
			@WebParam(name = "powerStatus", mode = WebParam.Mode.OUT, partName = "powerStatus") Holder<Integer> powerStatus,
			@WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result") Holder<Integer> result);

	/**
	 * Service definition of function api__QueryOnlineStatus
	 * 
	 * @param result
	 * @param loginID
	 * @param channelID
	 * @param onlineStatus
	 */
	@WebMethod(operationName = "QueryOnlineStatus")
	public void queryOnlineStatus(
			@WebParam(name = "loginID", partName = "loginID") String loginID,
			@WebParam(name = "channelID", partName = "channelID") int channelID,
			@WebParam(name = "onlineStatus", mode = WebParam.Mode.OUT, partName = "onlineStatus") Holder<Integer> onlineStatus,
			@WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result") Holder<Integer> result);

	/**
	 * Service definition of function api__QueryBatteryVoltage
	 * 
	 * @param result
	 * @param loginID
	 * @param voltage
	 * @param channelID
	 */
	@WebMethod(operationName = "QueryBatteryVoltage")
	public void queryBatteryVoltage(
			@WebParam(name = "loginID", partName = "loginID") String loginID,
			@WebParam(name = "channelID", partName = "channelID") int channelID,
			@WebParam(name = "voltage", mode = WebParam.Mode.OUT, partName = "voltage") Holder<Float> voltage,
			@WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result") Holder<Integer> result);

	/**
	 * Service definition of function api__QueryRealPlayRtspUrl
	 * 
	 * @param result
	 * @param loginID
	 * @param channelID
	 * @param rtspUrl
	 */
	@WebMethod(operationName = "QueryRealPlayRtspUrl")
	public void queryRealPlayRtspUrl(
			@WebParam(name = "loginID", partName = "loginID") String loginID,
			@WebParam(name = "channelID", partName = "channelID") int channelID,
			@WebParam(name = "rtspUrl", mode = WebParam.Mode.OUT, partName = "rtspUrl") Holder<String> rtspUrl,
			@WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result") Holder<Integer> result);

	/**
	 * Service definition of function api__QueryRecordFile
	 * 
	 * @param startTime
	 * @param result
	 * @param recordFileInfoList
	 * @param loginID
	 * @param channelID
	 * @param endTime
	 */
	@WebMethod(operationName = "QueryRecordFile")
	public void queryRecordFile(
			@WebParam(name = "loginID", partName = "loginID") String loginID,
			@WebParam(name = "channelID", partName = "channelID") int channelID,
			@WebParam(name = "startTime", partName = "startTime") String startTime,
			@WebParam(name = "endTime", partName = "endTime") String endTime,
			@WebParam(name = "recordFileInfoList", mode = WebParam.Mode.OUT, partName = "recordFileInfoList") Holder<String> recordFileInfoList,
			@WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result") Holder<Integer> result);

	
	@WebMethod(operationName = "Photograph")
	@WebResult(name = "result", partName = "result")
	public int photograph(
			@WebParam(name = "loginID", partName = "loginID") String loginID,
			@WebParam(name = "channelID", partName = "channelID") int channelID,
			@WebParam(name = "presetIndex", partName = "presetIndex") int presetIndex,
			@WebParam(name = "ftpPath", partName = "ftpPath") String ftpPath);	
		
}
